#pragma once
#ifndef ERROR_H
#define ERROR_H

#define ERROR_NO				0
#define ERROR_BRACKET_UNMATCH	-1
#define ERROR_VARITY_DUPLICATE	-2
#define ERROR_VARITY_COUNT_MAX	-3
#define ERROR_VARITY_NOSPACE	-4
#define ERROR_NONSEQ_GRAMMER	-5
#define ERROR_FUNC_ERROR    	-6
#define ERROR_FUNC_DUPLICATE	-7
#define ERROR_FUNC_COUNT_MAX	-8
#define ERROR_FUNC_ARGS			-9
#define ERROR_FUNC_RET_EMPTY	-10
#define ERROR_MISS_SEMICOLON	-11
#define ERROR_CONDITION_TYPE	-12
#define ERROR_VARITY_NONEXIST	-13
#define ERROR_CONST_ASSIGNED	-14
#define OK_FUNC_RETURN			-15

#define OK_NONSEQ_FINISH		1
#define OK_NONSEQ_INPUTING		2
#define OK_FUNC_INPUTING		3
#define OK_FUNC_FINISH			4
#define OK_FUNC_NOFUNC			5
#define OK_FUNC_CONTINUE_EXEC	6
#define OK_VARITY_DECLARE		7
#endif