#pragma once
#ifndef ERROR_H
#define ERROR_H

#define ERROR_NO				0
#define ERROR_BRACKET_UNMATCH	1
#define ERROR_VARITY_DUPLICATE	2
#define ERROR_VARITY_COUNT_MAX	3
#define ERROR_VARITY_NOSPACE	4
#define ERROR_NONSEQ_GRAMMER	5
#define OK_NONSEQ_FINISH		6
#define OK_NONSEQ_INPUTING		7
#define ERROR_FUNC_ERROR    	8
#define ERROR_FUNC_DUPLICATE	9
#define ERROR_FUNC_COUNT_MAX	10
#define OK_FUNC_INPUTING		11
#define OK_FUNC_FINISH			12
#define OK_FUNC_NOFUNC			13
#define OK_FUNC_CONTINUE_EXEC	14
#define OK_FUNC_RETURN			15
#define ERROR_FUNC_ARGS			16
#define ERROR_FUNC_RET_EMPTY	17
#define OK_VARITY_DECLARE		18
#define ERROR_MISS_SEMICOLON	19
#define ERROR_CONDITION_TYPE	20
#define ERROR_VARITY_NONEXIST	21
#endif